version: '3'
services:
  db:
    image: mysql
    volumes:
      - $HOME/srv/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nexus_db
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306:3306
    ports:
      - 3306:3306
    restart: always

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/nexus_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
