version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DATABASE=nexus_db
      - MYSQL_HOST=nexus-db.mysql.database.azure.com
      - MYSQL_USER=chrislee8684
      - MYSQL_PASSWORD=password@1

