version: '3.3'

services:
  db:
    image: mysql
    volumes:
      - $HOME/srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nexus_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DATABASE=nexus_db
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - ZIPCODE_API_KEY=${ZIPCODE_API_KEY} # Pass ZIPCODE_API_KEY from .env file
    depends_on:
      - db
